---
- hosts: all
  become: true
  tasks:
    - name: Update package index (Debian-based)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install python3-pip (Debian-based)
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (Debian-based)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Docker service (Debian-based)
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    
