---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python3-pip
        state: present

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start the container
      community.docker.docker_container:
        name: narayananraj
        image: "narayananraj/ansibledeploy"
        state: started
        published_ports:
          - "0.0.0.0:8080:8080"
