---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python3-pip
        state: present

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

        - name: Pull Apache Tomcat Docker image
      docker_image:
        name: tomcat
        tag: latest
        source: pull

    - name: Run Apache Tomcat container
      docker_container:
        name: tomcat
        image: tomcat:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"


          - name: Copy file with owner and permissions
      copy:
        src: target/*.war
        dest: /usr/local/tomcat/webapps/dockeransible.war
        mode: '0777'  # Using '0777' to set file permissions correctly
