---
- hosts: all
  become: true
  tasks:
    - name: Update package index (Debian-based)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install python3-pip (Debian-based)
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (Debian-based)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Docker service (Debian-based)
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Pull Apache Tomcat Docker image
      docker_image:
        name: tomcat
        tag: latest
        source: pull

    - name: Run Apache Tomcat container
      docker_container:
        name: tomcat
        image: tomcat:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: /var/lib/jenkins/workspace/ansible_deploy/target/dockeransible.war
        dest: /usr/local/tomcat/webapps/dockeransible.war
        mode: '0777'
